### ISSUE TITLE
Broken link to `ORACC` - exercice 1.2.3

### ISSUE THREAD

**Issue by KevinEtienne** [LispTO/llthw#13]
In exercise 1.2.3 the link (under `ORACC`) for the cuneiform fonts is broken. I see a white blank page.
See https://github.com/LispTO/llthw/blob/cdb30b408b2fb8f9d379837d81a32d9587a8d4db/book/1-02-03-unicode.md.

Maybe as an alternative link could go to wikipedia which contains a link to some cuneiform font packages, but this is a guess http://en.wikipedia.org/wiki/Cuneiform_%28Unicode_block%29#Font_packages.

**Comment by thephoeron** [comment]
Thanks for pointing this out.  The site should reflect this update momentarily.

**Comment by KevinEtienne** [comment]
Thanks that was quick :)

**Comment by thephoeron** [comment]
No problem!
