### ISSUE TITLE
Don't modify constant data in exercise 1.1.3

### ISSUE THREAD

**Issue by leuler** [LispTO/llthw#23]
Not to teach bad habits to the reader, I'd like to suggest to build the example lists in exercise 1.1.3 using LIST instead of QUOTE. Maybe additionally use elements that are self-evaluating to avoid having to write too many quotes, so
(defvar *test-list-a* (list 1 2 3))
I don't know whether it's didactically better to change the way how *test-list-b* is constructed, too.

**Comment by thephoeron** [comment]
Thanks! that's a valid point.  I have updated the exercise accordingly.
