### ISSUE TITLE
Where to begin contributing?

### ISSUE THREAD

**Issue by phoe** [LispTO/llthw#29]
I'm a fairly new Lisp hacker but I want to write notes as I learn and possibly turn them into parts of this book along the way as I research various topics for everyone's profit.
Where do I begin contributing to this though? LLTHW's webpage marks almost all chapters as pending review or incomplete. I'd also like some pointers from someone who's already working on the book so we don't duplicate each other's effort or otherwise miss each other's ideas and thoughts.

**Comment by thephoeron** [comment]
Thanks for your interest in Learn Lisp The Hard Way! We are not currently accepting new contributors, as the third draft is well under way and will be posted online once it is completed in full.

That being said, we are advocating both an "active reading" methodology and a greater emphasis on drills in the third draft, so you are certainly on the right track.  Feel free to post your notes and related research on your blog and let us know where to find them!

**Comment by phoe-krk** [comment]
Which exactly blog is on your mind? Do I have any default GitHub blog I'm oblivious of?

**Comment by thephoeron** [comment]
thanks!

**Comment by phoe-krk** [comment]
No problem! Please also give me a ping whenever the new draft goes online at the official WWW.

**Comment by phoe** [comment]
> Thanks for your interest in Learn Lisp The Hard Way! We are not currently accepting new contributors, as the third draft is well under way and will be posted online once it is completed in full.

I hereby express doubt in the latter part of the sentence after more than a year has passed without a single commit in this repository.

What's going on?

**Comment by thephoeron** [comment]
I've been working on it. Perfection takes time, but anything less isn't worth posting.

**Comment by phoe** [comment]
At least please let us know that this project isn't dead - and preferably post some information about progress.

**Comment by YanDoroshenko** [comment]
Bump.

**Comment by phoe** [comment]
Okay. I think I now know where to begin contributing.

Thanks, and sorry for my impatience when I was young and stupid.
