### ISSUE TITLE
Try Uncaught ReferenceError: MathJax is not defined

### ISSUE THREAD

**Issue by proehlen** [LispTO/llthw#37]
The MathJax CDN used in your "Try lisp" page is no longer working per:

https://www.mathjax.org/cdn-shutting-down/

There are alternative CDN links in the above article that can be used.  I tried cloning this repo and updating the link with the intention of creating a pull request with a fix but couldn't get llthw to run locally - sorry.

**Comment by thephoeron** [comment]
Thanks for pointing this out, the fix is live.
