### ISSUE TITLE
[website] Certificate expired

### ISSUE THREAD

**Issue by rprimus** [LispTO/llthw#43]
Mon Aug  6 09:18:27 BST 2018

The `Let's Encrypt` certificate has expired:

> Expired: Sunday, 22 July 2018 at 19:21:20 British Summer Time

Regards,

**Comment by L3rchal** [comment]
Why is this closed site still have expired certificate.

**Comment by rprimus** [comment]
Tue Nov  6 11:56:46 GMT 2018

@L3rchal:

Repo owner/site admin has not acknowledged nor responded to this issue.
Am closing all outstanding issues I've raised that are in this state.
